name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: Name of the artifact to deploy
                required: false
                default: dist
                type: string
            run-id:
                description: Run ID to download artifact from
                required: true
                type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read 
    steps:
      - name: Get code
        uses: actions/download-artifact@v4.3.0
        with:
            name: ${{ inputs.artifact-name }}
            run-id: ${{ inputs.run-id }}
      - name: list contents
        run: ls
      - name: output information
        run: echo "deploying and uploading"
